--liquibase formatted sql
--changeset abed:0001-01
CREATE TABLE sensitive_word
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bleep_word VARCHAR(255),
    CONSTRAINT pk_sensitiveword PRIMARY KEY (id)
);

ALTER TABLE sensitive_word
    ADD CONSTRAINT uc_sensitiveword_bleepword UNIQUE (bleep_word);